### ISSUE TITLE
question: how to use with custom scss colors

### ISSUE THREAD

**Issue by Dreamersoul** [JavaTMP/bootstrap-reverse#12]
greetings,
Thank you for the awesome work, i currently have my own custom `rtl.scss` file that fixes most of the issues i'm facing and it is working fine for now. however it is a pain to keep up to date.
I want to start using your bootstrap-reverse file however i have custom styling can we update the readme file to include how to do that with Webpack or rails?

I am willing to help maintain this project as it is of great importance to me.
good luck and thank you

**Comment by JavaTMP** [comment]
for custom styling or scss you can use yours before including our /src/sass/bootstrap-reverse.scss file and then your styling will override our ones
